name: test

on:
  project_card:
    types: [created]

jobs:
  echo-text:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Hello World
      run: echo "Hello, World!"
