name: Echo Text on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  echo-text:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Issue Created
        run: echo "A new issue has been created!"
