name: CI Pipeline

run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
      - 'release-*'
      - 'feature-*'
  pull_request:
    branches:
      - master
      - develop
      - 'release-*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 #fetch all branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install httpx
        pip install pytest-asyncio
        pip install fastapi
        pip install pydantic
        pip install pytest-cov
        pip install coverage
        pip install ruff

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run Pytest tests with coverage
      env:
        PYTHONPATH: ./src
      run: |
        python -m pytest --cov=src --cov-report=xml:reports/coverage.xml --cov-report=html:reports/htmlcov --junitxml=reports/xunit-result.xml

    # placeholder to add postman tests

    - name: Lint with Ruff
      run: ruff --output-format=github .
      continue-on-error: true

    - name: Wait to avoid timestamp issues
      run: sleep 10

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: . # Adjust this if your project is in a subdirectory
        args: >
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.python.version=3
          -Dsonar.branch.name=${{ github.ref_name }}
          -Dsonar.sources=src/
          -Dsonar.python.xunit.reportPath=reports/xunit-result.xml
          -Dsonar.python.coverage.reportPaths=reports/coverage.xml

    # check quality gate from sonarcube to fail the git pipeline if sonarcube shows a failure
    - name: Check SonarQube Quality Gate
      id: check_quality_gate
      run: |
        SONAR_PROJECT_KEY=kenlong2206_trade_assistant  
        SONAR_ORGANIZATION=kenlong2206 
        SONAR_HOST_URL="https://sonarcloud.io"
        
        # Make API call to get the quality gate status
        status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY&organization=$SONAR_ORGANIZATION" | jq -r .projectStatus.status)
        
        echo "Quality Gate status: $status"
        
        if [ "$status" != "OK" ]; then
          echo "Quality gate failed with status: $status"
          exit 1
        fi
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports
