name: CI

run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
      - 'release-*'
      - 'feature-*'
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install httpx
        pip install pytest-asyncio
        pip install fastapi
        pip install pydantic
        pip install tox
        pip install pytest-cov
        pip install coverage
        pip install ruff

    - name: Run tox to configure the tests
      run: tox -e py

    - name: Lint with Ruff
      run: ruff --output-format=github .
      continue-on-error: true

    - name: Run Pytest tests with coverage
      run: python -m pytest --cov=trade_assistant --cov-report=xml --junitxml=reports/xunit-result.xml

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: . # Adjust this if your project is in a subdirectory
        args: >
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.python.xunit.reportPath=reports/xunit-result.xml
          -Dsonar.python.coverage.reportPaths=reports/coverage.xml
          -Dsonar.python.version=3

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          reports/xunit-result.xml
          reports/coverage.xml
          
