name: Auto-create Feature Branch on Project Column Change

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: github.event.project_card.column_id == '<IN_PROGRESS_COLUMN_ID>'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create feature branch
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        ISSUE_URL: ${{ github.event.project_card.content_url }}
      run: |
        # Extract issue number and title
        ISSUE_NUMBER=$(curl -H "Authorization: token $TOKEN_GITHUB" $ISSUE_URL | jq .number)
        ISSUE_TITLE=$(curl -H "Authorization: token $TOKEN_GITHUB" $ISSUE_URL | jq -r .title)

        # Remove invalid characters from issue title to create a branch name
        BRANCH_NAME="feature/issue-${ISSUE_NUMBER}-$(echo "${ISSUE_TITLE}" | tr -cd '[:alnum:]-_')"

        # Create a new branch
        git checkout -b $BRANCH_NAME

        # Push the new branch to the remote repository
        git push -u origin $BRANCH_NAME

        # Add a comment to the issue
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
             -d "{\"body\": \"Feature branch [$BRANCH_NAME](https://github.com/${{ github.repository }}/tree/$BRANCH_NAME) created.\"}" \
             "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
